<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="generator" content="rustdoc"><meta name="description" content="A procedural macro that exposes internal errors to external errors the consuming applications should handle. It requires that the internal error implements [`error_support::ErrorHandling`]."><title>handle_error in error_support - Rust</title><script>if(window.location.protocol!=="file:")document.head.insertAdjacentHTML("beforeend","SourceSerif4-Regular-6b053e98.ttf.woff2,FiraSans-Italic-81dc35de.woff2,FiraSans-Regular-0fe48ade.woff2,FiraSans-MediumItalic-ccf7e434.woff2,FiraSans-Medium-e1aa3f0a.woff2,SourceCodePro-Regular-8badfe75.ttf.woff2,SourceCodePro-Semibold-aa29a496.ttf.woff2".split(",").map(f=>`<link rel="preload" as="font" type="font/woff2" crossorigin href="../static.files/${f}">`).join(""))</script><link rel="stylesheet" href="../static.files/normalize-9960930a.css"><link rel="stylesheet" href="../static.files/rustdoc-916cea96.css"><meta name="rustdoc-vars" data-root-path="../" data-static-root-path="../static.files/" data-current-crate="error_support" data-themes="" data-resource-suffix="" data-rustdoc-version="1.87.0 (17067e9ac 2025-05-09)" data-channel="1.87.0" data-search-js="search-e7298875.js" data-settings-js="settings-d72f25bb.js" ><script src="../static.files/storage-82c7156e.js"></script><script defer src="sidebar-items.js"></script><script defer src="../static.files/main-fb8c74a8.js"></script><noscript><link rel="stylesheet" href="../static.files/noscript-893ab5e7.css"></noscript><link rel="alternate icon" type="image/png" href="../static.files/favicon-32x32-6580c154.png"><link rel="icon" type="image/svg+xml" href="../static.files/favicon-044be391.svg"></head><body class="rustdoc attr"><!--[if lte IE 11]><div class="warning">This old browser is unsupported and will most likely display funky things.</div><![endif]--><nav class="mobile-topbar"><button class="sidebar-menu-toggle" title="show sidebar"></button></nav><nav class="sidebar"><div class="sidebar-crate"><h2><a href="../error_support/index.html">error_<wbr>support</a><span class="version">0.1.0</span></h2></div><div class="sidebar-elems"><section id="rustdoc-toc"><h2 class="location"><a href="#">handle_<wbr>error</a></h2><h3><a href="#">Sections</a></h3><ul class="block top-toc"><li><a href="#example" title="Example">Example</a></li></ul></section><div id="rustdoc-modnav"><h2 class="in-crate"><a href="index.html">In crate error_<wbr>support</a></h2></div></div></nav><div class="sidebar-resizer"></div><main><div class="width-limiter"><rustdoc-search></rustdoc-search><section id="main-content" class="content"><div class="main-heading"><div class="rustdoc-breadcrumbs"><a href="index.html">error_support</a></div><h1>Attribute Macro <span class="attr">handle_error</span><button id="copy-path" title="Copy item path to clipboard">Copy item path</button></h1><rustdoc-toolbar></rustdoc-toolbar><span class="sub-heading"><a class="src" href="../src/error_support_macros/lib.rs.html#63">Source</a> </span></div><pre class="rust item-decl"><code>#[handle_error]</code></pre><details class="toggle top-doc" open><summary class="hideme"><span>Expand description</span></summary><div class="docblock"><p>A procedural macro that exposes internal errors to external errors the
consuming applications should handle. It requires that the internal error
implements [<code>error_support::ErrorHandling</code>].</p>
<p>Additionally, this procedural macro has side effects, including:</p>
<ul>
<li>It would log the error based on a pre-defined log level. The log level is defined
in the [<code>error_support::ErrorHandling</code>] implementation.</li>
<li>It would report some errors using an external error reporter, in practice, this
is implemented using Sentry in the app.</li>
</ul>
<h2 id="example"><a class="doc-anchor" href="#example">§</a>Example</h2>
<div class="example-wrap ignore"><a href="#" class="tooltip" title="This example is not tested">ⓘ</a><pre class="rust rust-example-rendered"><code><span class="kw">use </span>error_support::{handle_error, GetErrorHandling, ErrorHandling};
<span class="kw">use </span>std::fmt::Display
<span class="attr">#[derive(Debug, thiserror::Error)]
</span><span class="kw">struct </span>Error {}
<span class="kw">type </span><span class="prelude-ty">Result</span>&lt;T, E = Error&gt; = std::result::Result&lt;T, E&gt;;

<span class="kw">impl </span>Display <span class="kw">for </span>Error {
    <span class="kw">fn </span>fmt(<span class="kw-2">&amp;</span><span class="self">self</span>, f: <span class="kw-2">&amp;mut </span>std::fmt::Formatter&lt;<span class="lifetime">'_</span>&gt;) -&gt; std::fmt::Result {
        <span class="macro">write!</span>(f, <span class="string">"Internal Error!"</span>)
    }
}

<span class="attr">#[derive(Debug, thiserror::Error)]
</span><span class="kw">struct </span>ExternalError {}

<span class="kw">impl </span>Display <span class="kw">for </span>ExternalError {
    <span class="kw">fn </span>fmt(<span class="kw-2">&amp;</span><span class="self">self</span>, f: <span class="kw-2">&amp;mut </span>std::fmt::Formatter&lt;<span class="lifetime">'_</span>&gt;) -&gt; std::fmt::Result {
        <span class="macro">write!</span>(f, <span class="string">"External Error!"</span>)
    }
}

<span class="kw">impl </span>GetErrorHandling <span class="kw">for </span>Error {
   <span class="kw">type </span>ExternalError = ExternalError;

   <span class="kw">fn </span>get_error_handling(<span class="kw-2">&amp;</span><span class="self">self</span>) -&gt; ErrorHandling&lt;<span class="self">Self</span>::ExternalError&gt; {
       ErrorHandling::convert(ExternalError {})
   }
}

<span class="comment">// The `handle_error` macro maps from the error supplied in the mandatory argument
// (ie, `Error` in this example) to the error returned by the function (`ExternalError`
// in this example)
</span><span class="attr">#[handle_error(Error)]
</span><span class="kw">fn </span>do_something() -&gt; std::result::Result&lt;String, ExternalError&gt; {
   <span class="prelude-val">Err</span>(Error{})
}

<span class="comment">// The error here is an `ExternalError`
</span><span class="kw">let _</span>: ExternalError = do_something().unwrap_err();</code></pre></div>
</div></details></section></div></main></body></html>